global:

templates:
  - "/etc/alertmanager/templates/*.tmpl"

route:
  group_wait: 0s
  group_interval: 5s
  repeat_interval: 3h

  receiver: nowhere

  group_by:
    - alertname
    - severity

  routes:
    # The real default receiver: this route will always match, and let the
    # alert continue to the other sibling routes.
    # Since it always matches, the parent route will never be used to process
    # the alert.
    - receiver: webhook-logger
      continue: true

    - matchers:
        - service=foobar
      receiver: slack

      #routes:
      #  - matchers:
      #      - severity="critical"
      #    receiver: slack
      #


inhibit_rules:
  - source_matchers:
      - severity="page"
    target_matchers:
      - severity="ticket"
    equal:
      - alertname

receivers:
  - name: nowhere

  - name: webhook-logger
    webhook_configs:
    - url: http://webhook-logger:8000/alerts
      send_resolved: true
      max_alerts: 0 # 0=all alerts

  - name: slack
    slack_configs:
      - send_resolved: true
        app_token_file: /etc/alertmanager/secrets/slack-app-token.secret
        channel: '{{ template "slack_channel" }}'
        color: '{{ template "slack_color" . }}'
        title: '{{ template "slack_title" . }}'
        text: '{{ template "slack_text" . }}'
